server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lfaguiar/{profile}
          repos:
            development:
              uri: https://github.com/lfaguiar/dev-config-repo
            production:
              uri: https://github.com/lfaguiar/prod-config-repo